server:
  port: 5000
spring:
  datasource:
    url: jdbc:postgresql://db-hackaton-trees.cqokpt4nuw0j.eu-central-1.rds.amazonaws.com/db_hackaton_trees
    username: postgres
    password: ${HACKATON_TREES_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    username: kovalchuk.roman03@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    port: 465
    protocol: smtps
    debug: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true
        auth: true

cloud:
  aws:
    credentials:
      access-key: ${S3_USER_ACCESS_KEY}
      secret-key: ${S3_USER_SECRET_KEY}
    region:
      static: eu-central-1
    stack:
      auto: false

amazon:
  s3:
    bucket:
      name: 4vesla

web:
  backend:
    host: ${WEB_BACKEND_HOST}
  frontend:
    host: ${WEB_FRONTEND_HOST}

jwt:
  secret: 4vesla